services:
  - name: pathforge-backend
    env: python
    rootDirectory: backend/
    buildCommand: |
      set -x # This will print each command before execution for debugging
      pip install -r requirements.txt
    startCommand: "gunicorn core.wsgi:application --bind 0.0.0.0:$PORT"
    preDeployCommand: python manage.py collectstatic --noinput
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
