services:
  - type: web
    name: pathforge-backend
    env: python
    rootDirectory: backend/
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
      # --- TEMPORARY: Create superuser using a dedicated script ---
      # This script will create a superuser if one doesn't exist.
      # You can modify the default username/password directly in the create_admin_user.py file.
      # Make sure to remove this line after you successfully log in!
      python create_admin_user.py
      # --- END TEMPORARY SECTION ---
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
