services:
  - type: web
    name: pathforge-backend
    env: python
    rootDirectory: backend/
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
      # --- TEMPORARY: Create superuser on Render's database ---
      # This command will create a superuser if one doesn't exist.
      # Make sure to remove these lines after you successfully log in!
      python manage.py shell -c "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(username='mynewadminuser').exists() or User.objects.create_superuser('mynewadminuser', 'admin@example.com', 'MyStrongTempPassword123!')"
      # --- END TEMPORARY SECTION ---
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
