services:
  - type: web
    name: pathforge-backend
    env: python
    rootDirectory: backend/
    buildCommand: |
      set -x # This will print each command before execution for debugging
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
      # --- TEMPORARY: Create superuser using a dedicated script ---
      # This uses django-extensions to run the script.
      python manage.py runscript create_admin_user
      # --- END TEMPORARY SECTION ---
    startCommand: "python -m gunicorn core.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
