# Generated by Django 5.2.3 on 2025-07-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="source",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
